name: Build and package DATE_EXTRA plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@main
    with:
      plugin_name: date-extra
      plugin_directory: date_extra
      build_target: date_extra
      plugin_library: date_extra.so

      sdk_image: quay.io/lefred14/mariadb-plugin-build
      mariadb_versions: |
          13.0.2
          13.1.1
          
      cmake_options: -DPLUGIN_DATE_EXTRA=DYNAMIC
      test_suite: date_extra
      run_tests: false
